name: jokenpo_app
description: "Jogo Jokenpo em Flutter - Projeto 01 APM 251"
# A linha abaixo impede que o pacote seja publicado acidentalmente no pub.dev.
publish_to: 'none' # Remova esta linha se desejar publicar no pub.dev

# Versão do aplicativo
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependências do projeto
dependencies:
  flutter:
    sdk: flutter

  # Adiciona ícones no estilo Cupertino (iOS)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints recomendados para boas práticas de codificação
  flutter_lints: ^5.0.0

# Configurações específicas do Flutter
flutter:
  uses-material-design: true

  # Adicione suas imagens aqui
  assets:
    - assets/images/pedra.jpeg
    - assets/images/papel.jpeg
    - assets/images/tesoura.jpeg
    - assets/images/pedra2.jpeg
    - assets/images/papel2.jpeg
    - assets/images/tesoura2.jpeg

  # Para adicionar fontes personalizadas, descomente e edite a seção abaixo
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
